### PR TITLE
update tsv and upload script to reflect new policy

### PR DESCRIPTION
**Pull request by htried**
see title!

phab ticket: https://phabricator.wikimedia.org/T355696

### CODE REVIEW

**Comment by nshahquinn** [comment]
Thank you for putting this together! My thoughts:
- I would name the new fields `data_risk_score` and `data_risk_classification`. We may have other risk ratings in the future, so it's helpful to disambiguate. By that logic, `is_protected` should be `data_is_protected`, but I think we need to maintain backward compatibility there. `classification` is just because we have two fields named "classification" already, so we might as well be consistent if there's no particular reasoning behind `designation`.
- It looks like the TSV is a little messed up. If you view it in GitHub, there's a notice saying: "We can make this file [beautiful and searchable](https://docs.github.com/articles/rendering-csv-and-tsv-data) if this error is corrected: It looks like row 2 should actually have 22 columns, instead of 23. in line 1." This probably has something to do with two field headers getting merged into "is_imf_data_entitis_world_bank_data_entity".
- The booleans are serialized in all caps when previously they were just in initial caps ("TRUE" vs "True"). Not sure how much that matters, but initial caps is the format that Pandas uses (because Python, I assume) and it seems reasonable to stick with that.
- Would it make sense to eliminate the word "risk" from the classifications, so we have "higher", "lower", "no publication"? Not important; totally fine if you want to keep it as is. 
- Please add the new fields to the data readme (country/README.md) 😁

**Comment by htried** [comment]
just updated to be in line with comments! going to keep "risk" in the data classifications, even though its a bit redundant, so that it lines up with the terminology used in the policy

**Comment by nshahquinn** [comment]
Thank you for the updates! I noticed one big issue remaining and have two small suggestions for the documentation.

The big issue: unfortunately, the TSV is still broken. A number have of records have problems where `grant_committee_region` is smushed into `wikimedia_region` and as a result all the subsequent fields are shifted over one. Others have a similar problem starting with `form_990_region`. Now that the booleans are in the same format is before, it should be easier to see in the overall PR diff.

(I also noticed that a number of countries like Cape Verde and the Czech Republic have "Antarctica" as their `form_990_region` but it turns out that was introduced some time ago, so this new bug actually helped uncover an old one! Thank you 🤣)

Documentation suggestions:
- make the mapping of scores to classifications into a Markdown table
- use the "includes null value" note for `data_risk_score` (you can see an example in `un_m49_code`).

Once you handle these, we should be good to merge! I will hold off on fixing the Antartican imperialism issue until afterwards to make things simpler since it's not particularly urgent.

**Comment by htried** [comment]
Sorry for the multiple pushes, but I think it's fixed! no more errors except for inadvertent Antarctic supremacy

**Pull request merged**
