### PR TITLE
T342707 expand canonical contries w/gdi columns

### PR DESCRIPTION
**Pull request by andrewtavis-wmde**
## Description

As discussed in [T342703](https://phabricator.wikimedia.org/T342703) and in a [thread on Slack](https://wikimedia.slack.com/archives/CLKDS4MG9/p1698341191877799), we would like to move the useful columns from the `gdi.country_meta_data` over to `canonical_data.countries` so we have a single canonical source. WMDE will be using this table for analysis of Wikidata usage: see [T345262](https://phabricator.wikimedia.org/T345262).

Next step here would be for someone with write access for this table to run the [data update notebook](https://github.com/wikimedia-research/canonical-data/blob/master/country/upload_to_data_lake.ipynb) in this repository. Happy to assist with this, but having someone from WMF to check that all's well would be appreciated!

I'll send an HTML of the notebook used to combine the tables to the aforementioned Slack thread :) 

Please let me know if further steps are needed!

CC @Mayakpwiki, @hghani-ctr as directed to on Slack

### CODE REVIEW

**Comment by andrewtavis-wmde** [comment]
Message on Slack with the HTML for the work done is [here](https://wikimedia.slack.com/archives/CLKDS4MG9/p1699618108249619?thread_ts=1698341191.877799&cid=CLKDS4MG9). Best to download it and open in browser :blush:

**Review by nshahquinn — CHANGES_REQUESTED** [review]
@andrewtavis-wmde thank you for putting all of this together!

There's one important thing to add:
* Documentation for the new fields in `country/README.md`. I decided to make that the main location and link to it from Datahub, since Datahub isn't publicly accessible.

Some final suggestions about field names:
* `qid`  → `wikidata_id` ("QID" is jargon and likely to confuse some)
* `is_wb_data_entity` → `is_world_bank_data_entity` (unlike UN and IMF, "WB" isn't a well-known abbreviation)
* `is_pwt_data_entity` → `is_penn_world_table_data_entity` (same as above)
* `wmf_market_research` → `market_research_classification` (WMF is unnecessary disambiguation, and it feels like a word is missing without "classification")

One note for the record:
* this removes the "--"/"unknown" entry, which we wanted to do anyway ([T345123](https://phabricator.wikimedia.org/T345123))

**Comment by andrewtavis-wmde** [comment]
Hey @nshahquinn :wave: FYI I'll be hopefully getting to this by the end of the week or early next week. I need to jump onto a task I'm doing for your all's Search Team and then this jumps to the highest priority :)

**Comment by andrewtavis-wmde** [comment]
Hey @nshahquinn! :wave: Sorry that it took a bit longer for me to get to this than expected. 33feb86 sends along changes to the column names as indicated, updates the documentation and fixes some `NA` values to be `Unclassified` that I found while doing the documentation. 

You can see how the docs are looking [on my branch](https://github.com/andrewtavis-wmde/canonical-data/tree/T342703-canonical-countries-cols/country). I hope it's looking alright! I tried to follow the original style, but added in annotation for the data type and what kind of values the user can be expected in a uniform way rather than just for booleans in the description. I also added in notes and warnings using [GitHub syntax to highlight them](https://github.com/orgs/community/discussions/16925). 

Please note that `form_990_region` doesn't include a description in the docs right now as I really was not sure what it was referring to (I was getting something for the IRS, but maybe that's not it).

I'm at Chaos Communication Congress in Hamburg next week and won't be able to make any changes here. Please feel free to make any changes you'd like, and I'd of course be happy to send along some changes in the first week of the year when I'm back!

Thanks again for the review!

**Comment by andrewtavis-wmde** [comment]
Also note that 84cf5be changed the data type of `un_m49_code` to `String` in the docs, which is the case, but because we have `Unclassified` for Taiwan and Kosovo. Not ideal to have that be a string, but then having the "null" values be consistent also will help people find them more easily. Let me know if you have suggestions though!

**Comment by nshahquinn** [comment]
Thank you, @andrewtavis-wmde! This is looking great. Your changes to the doc style are real improvements 😁

The only actual issue I noticed is that the "emerging" classification comes from [a 2014 internal classification](https://meta.wikimedia.org/wiki/Community_Engagement/Defining_Emerging_Communities) rather than the IMF or the World Bank. I can definitely make the update myself and add a description for the form 990 classification while I'm at it (it does actually relate to the IRS thing you found although I can see why it didn't seem right).

I actually think it would be more sensible to use actual nulls (represented by empty values in the TSV) than string values of "unclassified". I assume you carried the "unclassified" over from the source table?

**Comment by andrewtavis-wmde** [comment]
> I actually think it would be more sensible to use actual nulls (represented by empty values in the TSV) than string values of "unclassified". I assume you carried the "unclassified" over from the source table?

Yes exactly, @nshahquinn. I just figured the best thing was to keep them as they were in the GDI table.

Glad that the doc changes were helpful!

**Comment by andrewtavis-wmde** [comment]
The GDI table also had `YES` and `NO` for some columns, which I converted over to `True` and `False`.

**Comment by andrewtavis-wmde** [comment]
> The only actual issue I noticed is that the "emerging" classification comes from a 2014 internal classification rather than the IMF or the World Bank

And re this: thanks for the catch! I saw a map on this in the [Global North and Global South Wikipedia Page](https://en.wikipedia.org/wiki/Global_North_and_Global_South#Challenges) and figured that the citation for that should be the one that should be here :)

**Comment by nshahquinn** [comment]
@andrewtavis-wmde FYI, I edited your commit messages. The only reason was that I copied the bug number from your commit messages and realized after I was done that it was the wrong number. So, even though there was no real need, I decided I would try to correct it in my commits, and once I started doing that I figured I would correct it in yours too, and while I was in the process I couldn't help myself from tweaking a few other things. I hope you don't mind! 😅 

Anyway, this is all done and I think we are GOOD TO GO! 🚀 🎉

**Comment by andrewtavis-wmde** [comment]
Don't mind at all, @nshahquinn! Thanks so much for the review and quality checks for the commits!

**Pull request merged**
