### PR TITLE
Indicate EU membership in country dataset and switch to TSV

### PR DESCRIPTION
**Pull request by marcelrf**
This change adds a new boolean field "is_eu" to the canonical_data.countries dataset. The field is True whenever the corresponding country belongs to the European Union, and is False otherwise. See: https://european-union.europa.eu/principles-countries-history/country-profiles_en

### CODE REVIEW

**Comment by nshahquinn** [comment]
@marcelrf I noticed that some EU special territories with their own entries (Åland, French Guiana, Guadeloupe, Saint Martin, and Mayotte) do not have `in_eu` set. Are you okay with me modifying that? (I looked at https://en.wikipedia.org/wiki/Special_territories_of_members_of_the_European_Economic_Area to figure out which territories are and are not part of the EU).

**Comment by marcelrf** [comment]
@nshahquinn Oh! Of course, please feel free to change that. Or I can change it and update the table already if you prefer.
Thanks for the useful link! I see there that `Martinique` and `Réunion` are also listed as pertaining in the EU, no?

**Comment by nshahquinn** [comment]
> Or I can change it and update the table already if you prefer.

Actually, I think that would be easier since this is coming from a branch in your fork.

The current update process actually leaves one row broken due to [T327983](https://phabricator.wikimedia.org/T327983). I had written [a patch](https://github.com/wikimedia/wmfdata-python/pull/41) for `wmfdata.hive.load_csv`, but that doesn't work either.

For now, I think the best workaround is to write the CSV differently ([T327983](https://phabricator.wikimedia.org/T327983) shows how to do that with Pandas). Then, `load_csv` will either work correctly immediately or with the addition of a line to the underlying SQL. 

If you want to do the loading, feel free. Otherwise, just update the CSV for this PR as normal and I can rewrite and load it. I've been thinking about this and am planning to make some documentation improvements anyway.

> Thanks for the useful link! I see there that `Martinique` and `Réunion` are also listed as pertaining in the EU, no?

Ah, yes, of course, I just missed those.

**Comment by marcelrf** [comment]
I marked the special territories as belonging to the EU in the file. Including both the ones you found and the 2 I found.
I also changed the format of the file to a tsv, so that the commas in the line `Bonaire, Sint Eustatius, and Saba	BQ	Global North	North America	False	False` are no longer a problem.
And finally, modified the notebook code to pass in the tab separator to the load_csv method.

**Comment by nshahquinn** [comment]
Thank you! Good idea to use TSV instead; I had forgotten that `load_csv` had that parameter.

**Pull request merged**
